<!-- credit: adapted from https://github.com/AArnott/Library.Template -->
<Project>
  <PropertyGroup>
    <Configuration Condition=" '$(Configuration)' == '' ">Debug</Configuration>
    <RepoRootPath>$(MSBuildThisFileDirectory)</RepoRootPath>
    <BaseIntermediateOutputPath>$(RepoRootPath)obj\$([MSBuild]::MakeRelative($(RepoRootPath), $(MSBuildProjectDirectory)))\</BaseIntermediateOutputPath>
    <BaseOutputPath Condition=" '$(BaseOutputPath)' == '' ">$(RepoRootPath)bin\$(MSBuildProjectName)\</BaseOutputPath>
    <PackageOutputPath>$(RepoRootPath)bin\Packages\$(Configuration)\</PackageOutputPath>
    <LangVersion>Latest</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);CS1587;CS1591;CS8604;SA1012;SA1013;SA1024;SA1028;SA1101;SA1116;SA1117;SA1127;SA1132;SA1201;SA1202;SA1203;SA1204;SA1214;SA1300;SA1309;SA1310;SA1401;SA1402;SA1413;SA1502;SA1505;SA1507;SA1508;SA1513;SA1514;SA1518;SA1600;SA1602;SA1633;SA1649;SA1618</NoWarn>
    <ProduceReferenceAssembly>true</ProduceReferenceAssembly>

    <EnableDynamicPlatformResolution>true</EnableDynamicPlatformResolution>

    <DebugType Condition=" '$(CI)' != 'true' ">embedded</DebugType>
    <DebugType Condition=" '$(CI)' == 'true' ">portable</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <IncludeSymbols Condition=" '$(CI)' == 'true' ">true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <AllowedOutputExtensionsInPackageBuildOutputFolder>$(AllowedOutputExtensionsInPackageBuildOutputFolder);.pdb</AllowedOutputExtensionsInPackageBuildOutputFolder>
    <ContinuousIntegrationBuild Condition=" '$(CI)' == 'true' ">true</ContinuousIntegrationBuild>

    <Company>Json.Path</Company>
    <Authors>Json.Path Maintainers</Authors>
    <Copyright>© Json.Path Maintainers. All rights reserved.</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <EnableSourceControlManagerQueries Condition=" '$(CI)' != 'true' ">false</EnableSourceControlManagerQueries>
    <EnableSourceLink Condition=" '$(CI)' != 'true' ">false</EnableSourceLink>
    <SourceLinkCreate Condition=" '$(CI)' != 'true' ">false</SourceLinkCreate>
    <RepositoryUrl>https://github.com/myarichuk/Json.Path</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/myarichuk/Json.Path</PackageProjectUrl>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>json;path;query</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <None Include="$(MSBuildThisFileDirectory)README.md">
      <Pack>true</Pack>
      <PackagePath>README.md</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="all" />
    <PackageReference Include="StyleCop.Analyzers.Unstable" Version="1.2.0.556" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <AdditionalFiles Include="$(MSBuildThisFileDirectory)stylecop.json" Link="stylecop.json" />
  </ItemGroup>

  <ItemDefinitionGroup>
    <PackageReference GeneratePathProperty="true" />
  </ItemDefinitionGroup>
</Project>
